//! GRAPH_REPORT.md renderer (Graphify-compatible sections).

use crate::analyze::{confidence_breakdown, find_import_cycles};
use crate::schema::{Analysis, DetectionResult, GraphJson, TokenCost};

/// Generate GRAPH_REPORT.md content.
pub fn render_report(
    graph: &GraphJson,
    analysis: &Analysis,
    detection: &DetectionResult,
    token_cost: &TokenCost,
    root_label: &str,
    built_at_commit: Option<&str>,
) -> String {
    let today = today_iso();

    let (ext, inf, amb) = confidence_breakdown(graph);
    let total = (ext + inf + amb).max(1);
    let ext_pct = ext * 100 / total;
    let inf_pct = inf * 100 / total;
    let amb_pct = amb * 100 / total;

    let mut lines = vec![
        format!("# Graph Report - {root_label}  ({today})"),
        String::new(),
        "## Corpus Check".into(),
    ];

    if let Some(w) = &detection.warning {
        lines.push(format!("- {w}"));
    } else {
        lines.push(format!(
            "- {} files · ~{} words",
            detection.total_files, detection.total_words
        ));
        lines.push(
            "- Verdict: corpus is large enough that graph structure adds value.".into(),
        );
    }

    lines.push(String::new());
    lines.push("## Summary".into());
    lines.push(format!(
        "- {} nodes · {} edges · {} communities",
        graph.nodes.len(),
        graph.links.len(),
        analysis.communities.len()
    ));
    lines.push(format!(
        "- Extraction: {ext_pct}% EXTRACTED · {inf_pct}% INFERRED · {amb_pct}% AMBIGUOUS"
    ));
    lines.push(format!(
        "- Token cost: {} input · {} output",
        token_cost.input, token_cost.output
    ));

    if let Some(commit) = built_at_commit {
        lines.push(String::new());
        lines.push("## Graph Freshness".into());
        let short = if commit.len() > 8 { &commit[..8] } else { commit };
        lines.push(format!("- Built from commit: `{short}`"));
        lines.push("- Run `git rev-parse HEAD` and compare to check if the graph is stale.".into());
        lines.push("- Run `graphify update .` after code changes (no API cost).".into());
    }

    if !analysis.community_labels.is_empty() {
        lines.push(String::new());
        lines.push("## Community Hubs (Navigation)".into());
        for (cid, label) in &analysis.community_labels {
            let size = analysis
                .communities
                .get(cid)
                .map(|m| m.len())
                .unwrap_or(0);
            if size == 0 {
                continue;
            }
            lines.push(format!("- {label} ({size} nodes)"));
        }
    }

    lines.push(String::new());
    lines.push("## God Nodes (most connected - your core abstractions)".into());
    if analysis.god_nodes.is_empty() {
        lines.push("- None detected.".into());
    } else {
        for (i, g) in analysis.god_nodes.iter().enumerate() {
            lines.push(format!("{}. `{}` - {} edges", i + 1, g.label, g.degree));
        }
    }

    lines.push(String::new());
    lines.push("## Surprising Connections (you probably didn't know these)".into());
    if analysis.surprises.is_empty() {
        lines.push(
            "- None detected - all connections are within the same source files.".into(),
        );
    } else {
        for s in &analysis.surprises {
            lines.push(format!(
                "- `{}` --{}--> `{}`  [{}]",
                s.source, s.relation, s.target, s.confidence
            ));
            lines.push(format!("  {} → {}", s.source_files[0], s.source_files[1]));
        }
    }

    let has_code = graph.nodes.iter().any(|n| n.file_type.as_str() == "code")
        || graph
            .links
            .iter()
            .any(|e| e.relation == "imports" || e.relation == "imports_from");
    if has_code {
        let cycles = find_import_cycles(graph);
        lines.push(String::new());
        lines.push("## Import Cycles".into());
        if cycles.is_empty() {
            lines.push("- None detected.".into());
        } else {
            for c in cycles {
                lines.push(format!("- {}", c.join(" → ")));
            }
        }
    }

    lines.push(String::new());
    lines.push("## Suggested Questions".into());
    for q in &analysis.suggested_questions {
        lines.push(format!("- **{}**", q.question));
        lines.push(format!("  _{}_", q.why));
    }

    lines.push(String::new());
    lines.push("---".into());
    lines.push(
        "*Generated by ds-graphify (Graphify-compatible native pipeline). Query with `graphify query`, `graphify path`, `graphify explain`.*".into(),
    );

    lines.join("\n") + "\n"
}

fn today_iso() -> String {
    // Prefer `date -u +%Y-%m-%d` for portability without chrono dep.
    if let Ok(out) = std::process::Command::new("date")
        .args(["-u", "+%Y-%m-%d"])
        .output()
        && out.status.success()
    {
        return String::from_utf8_lossy(&out.stdout).trim().to_string();
    }
    "unknown".into()
}
