#!/usr/bin/env python3
"""Regenerate or verify ``src/prompt/prompt_encrypted.rs``.

Run from any directory:

    python3 scripts/encrypt_templates.py
    python3 scripts/encrypt_templates.py --check

The XOR encoding is obfuscation only; the seeds are intentionally stored in
this repository. ``--check`` is suitable for CI and exits nonzero when the
checked-in generated file is missing or stale.
"""

import argparse
import sys
from pathlib import Path
from typing import Dict, Optional, Sequence

SEEDS: Dict[str, int] = {
    "BASE_PROMPT_ENC": 0x5A,
    "CODEX_PROMPT_ENC": 0x7B,
    "SUBAGENT_PROMPT_ENC": 0x3D,
}
TEMPLATES: Dict[str, str] = {
    "BASE_PROMPT_ENC": "prompt.md",
    "CODEX_PROMPT_ENC": "apply_patch_prompt.md",
    "SUBAGENT_PROMPT_ENC": "subagent_prompt.md",
}

SCRIPT_DIR = Path(__file__).resolve().parent
CRATE_DIR = SCRIPT_DIR.parent
TEMPLATE_DIR = CRATE_DIR / "templates"
OUT_PATH = CRATE_DIR / "src" / "prompt" / "prompt_encrypted.rs"


def xor_encrypt(data: bytes, seed: int) -> bytes:
    """Apply the position-dependent XOR used by the Rust decryptor."""

    return bytes(byte ^ ((seed + index) & 0xFF) for index, byte in enumerate(data))


def render_output() -> str:
    """Return the complete deterministic Rust source for the encrypted data."""

    lines = [
        "// Auto-generated -- do not edit.",
        "// Regenerate: python3 scripts/encrypt_templates.py",
        "// Verify: python3 scripts/encrypt_templates.py --check",
        "// XOR-encrypted prompt templates (key = position-dependent seed).",
        "",
    ]
    for const_name, filename in TEMPLATES.items():
        path = TEMPLATE_DIR / filename
        if not path.is_file():
            raise FileNotFoundError(f"missing prompt template: {path}")
        encrypted = xor_encrypt(path.read_bytes(), SEEDS[const_name])
        byte_array = ", ".join(str(byte) for byte in encrypted)
        # Keep each generated byte array on one line so rustfmt does not
        # reflow thousands of elements on every formatting run.
        lines.append("#[rustfmt::skip]")
        lines.append(f"pub(crate) const {const_name}: &[u8] = &[{byte_array}];")
        lines.append("")

    seeds = ", ".join(f"0x{seed:02X}" for seed in SEEDS.values())
    lines.append(f"pub(crate) const PROMPT_SEEDS: [u8; {len(SEEDS)}] = [{seeds}];")
    lines.append("")
    return "\n".join(lines)


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated file is current without modifying it",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    expected = render_output()

    if args.check:
        if not OUT_PATH.is_file():
            print(f"ERROR: generated prompt file is missing: {OUT_PATH}", file=sys.stderr)
            return 1
        actual = OUT_PATH.read_text(encoding="utf-8")
        if actual != expected:
            print(
                "ERROR: prompt_encrypted.rs is stale; run "
                "`python3 scripts/encrypt_templates.py`.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUT_PATH.relative_to(CRATE_DIR)} is current")
        return 0

    OUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(CRATE_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
